var res = (10 == 10); 
var res2 = (10 == 10) && (9 == 9); 
var res3 = (10 == 10) && (8 == 9); 
var res4 = (10 == 19) && (8 == 9); 
var res5 = (10 == 10) && (9 == 9); 
var res6 = true && true; 
var res7 = true && "true"; 
var res8 = true && "true1"; 
var res9 = true && !!"true1"; 

console.log("var res = (10 == 10)"); 
console.log("|| 1 - ", res); 
console.log("&& 1 - ", res); 
console.log("! 1 - ", !res); 
console.log("var res2 = (10 == 10) && (9 == 9)"); 
console.log("|| 2 - ", res2); 
console.log("&& 2 - ", res2);
console.log("! 2 - ", !res2);  
console.log("var res3 = (10 == 10) && (8 == 9)"); 
console.log("|| 3 - ", res3); 
console.log("&& 3 - ", res3); 
console.log("! 3 - ", !res3); 
console.log("var res4 = (10 == 19) && (8 == 9)"); 
console.log("|| 4 - ", res4); 
console.log("&& 4 - ", res4); 
console.log("! 4 - ", !res4); 
console.log("var res5 = (10 == 10) && (9 == 9)"); 
console.log("|| 5 - ", res5); 
console.log("&& 5 - ", res5); 
console.log("! 5 - ", !res5); 
console.log("var res6 = true && true"); 
console.log("|| 6 - ", res6); 
console.log("&& 6 - ", res6); 
console.log("! 6 - ", !res6); 
console.log("var res7 = true && 'true'"); 
console.log("|| 7 - ", res7); 
console.log("&& 7 - ", res7); 
console.log("! 7 - ", !res7); 
console.log("var res8 = true && 'true1'"); 
console.log("|| 8 - ", res8); 
console.log("&& 8 - ", res8); 
console.log("! 8 - ", !res8); 
console.log("var res9 = true && !!'true1'"); 
console.log("|| 9 - ", res9); 
console.log("&& 9 - ", res9); 
console.log("! 9 - ", !res9); 
console.log("!! 9 - ", !!res9); //tipo original
